//Author: James B & Koby S
//Date: May 31, 2022
//Computer Science culminating project

import java.util.*;

public class wordletest {
    public static void main(String[] args) {
        //Initialize the wordlist, containing only 5-letter words
        String[] wordlist = {"cheek", "apple", "heart", "knead", "smell"};
        //Choose a random word from the wordlist by choosing a random index within the word list 
        // and choosing the word assigned to that index
        int word = (int)(Math.random() * wordlist.length);
        String autoword = wordlist[word];
        
        
        //convert chosen string to an arraylist in order to compare each letter and to print it in the GUI
        //use the split function to split when there is no space character in the string, then print it
        String[] splitString = autoword.split("");
        print(splitString);
        
        //Initialize the word the user guesses
        String guess = "";
        
        //initialize a scanner and ask the user for an input. If the user does not input a 5 letter word, the game asks again.
        Scanner sc = new Scanner(System.in);
        while (guess.length() != 5) {
            System.out.println("guess a word");
            guess = sc.nextLine();
        }
        
        //use the split function to split the autogenerated and user guess into arrays for comparison
        String[] chosen = split(autoword);
        
        String[] guessnew = split(guess);
        
        //print out the user's guess
        print(guessnew);
        

        
        System.out.println("\n");
        
        //print out the colours of each letter (green, yellow, grey) in number format
        printInt(check(chosen, guessnew));
    }
    public static void print(String[] words) {
    
        for (int i = 0; i < words.length;i++) {
            System.out.print(words[i] + " ");
            }
        
        
    }
    public static void printInt(int[] nums) {
        for (int i = 0; i < nums.length; i++) {
            System.out.print(nums[i] + " ");
        }
    }
    
    //split function uses the .split() String method to split a string into a String array 
    //where each index is a seperate letter in the string
    //In this case, we split when there is no space character as every input is a single word
    public static String[] split(String word) {
        String[] splitString = word.split("");
        return splitString;
    }
    
    //This function compares the two given strings and checks whether a letter should be green, yellow, or grey
    public static int[] check(String[] autoword, String[] guess) {
        int[] ans = new int[autoword.length];
        
        //iterate through the words and compare
        for (int i = 0; i < autoword.length; i++) {
            //if both letters are the same, the colour for this space is green
            if (autoword[i].equals(guess[i])) {
                
                ans[i] = 2;
                continue;
            //if the letter is not in the same position, but elsewhere in the auto generated word, this space becomes yellow.
            } else if (letter_In_String(autoword, guess, i)) {
                ans[i] = 1;
            //if nothing matches, this space is grey
            } else {
                ans[i] = 0;
            }
            
            
        }
        return ans;
    }
    //this function checks whether a certain letter is in the auto generated word.
    //It iterates through the word and compares each letter to the given letter in the user's guess. 
    //If the letter is found and is not in the same position as the given letter from the user's guess, return true. Otherwise, false.
    public static boolean letter_In_String(String[] autoword, String[] guess, int i) {
        for (int k = 0; k < autoword.length; k++) {
                if (guess[i].equals(autoword[k]) && i != k) {
                    return true;
                    
                }
                
        }
        return false;
    }
}
